/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/MarketData': RouteRecordInfo<'/MarketData', '/MarketData', Record<never, never>, Record<never, never>>,
    '/nav/Account': RouteRecordInfo<'/nav/Account', '/nav/Account', Record<never, never>, Record<never, never>>,
    '/nav/Market': RouteRecordInfo<'/nav/Market', '/nav/Market', Record<never, never>, Record<never, never>>,
    '/nav/StockInfo': RouteRecordInfo<'/nav/StockInfo', '/nav/StockInfo', Record<never, never>, Record<never, never>>,
    '/nav/Trade': RouteRecordInfo<'/nav/Trade', '/nav/Trade', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
  }
}
